---
name: run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      DAGGER_CACHE_FROM: type=gha,scope=gc-durbinlab-bucket
      DAGGER_CACHE_TO: type=gha,mode=max,scope=gc-durbinlab-bucket
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dagger
        uses: dagger/dagger-for-github@v4
        with:
          cmds: |
            project update
            do test
